---
title: "Syllabus"
---
## Goals and Expectations
### Course Description
In this interdisciplinary course, students are asked to engage with environmental justice — a social movement and form of inquiry intended to rectify the inequitable distribution of environmental benefit and burden — both theoretically and methodologically. Students will examine five forms of justice: distributional, recognitional, procedural, restorative, and cosmopolitan, and be invited to apply them to weekly community-level case studies. Using a combination of theory and introductory data visualization skills, we will learn from past injustices, explore present interventions, and imagine more equitable realities.

### Measurable Outcomes
1. **Demonstrate an understanding of the nuances of an intersectional approach** (i.e., how systems of power can reinforce oppression of land and people) and their applications to environmental injustice.
2. **Reflect on how your positionality and lived experiences** shape your approach to environmental justice. 
3. **Assess empirical patterns of environmental injustice in US communities** related to Food, Energy, and Water (FEW nexus). 
4. **Identify opportunities and challenges beyond distributional justice** (procedural, recognitional, restorative, and cosmopolitan justice) for environmental solutions spatially and temporally.
5. **Suggest opportunities for intervention** by developing a theory-driven logic model.


## Course Community
### Teaching, Learning, and Being in Community
I hope that students not only take away the skills associated with the course's measurable outcomes, but also learn more about themselves, their peers, and the environment around them. This requires a certain level of vulnerability and trust, which I hope that we can establish together. 

I also designed this course to help students foster community beyond the classroom, so that they too can go on to build expansive, solution-oriented movements that welcome everyone into a collective vision of what the world could be. I share some of adrienne marie brown's [^1] points on social justice and community, that may be useful to ask of yourself and others throughout this course:

- How can we invite our peers into belonging? 
- How can we create conditions that ensure dignity for each person? 
- How can we challenge regressive beliefs meant to divide us, and remind one another that we belong to this planet, and each other? 
- How can we forge communities that not only survive, but can imagine more equitable realities?


### Shared Expectations
In this course, we intend to be accountable to one another by... 
- Stories stay, lessons leave
- Take space, leave space
- Prepare & Engage
- Bring the classroom community out
- Apply work to ongoing life/events
- Centering Humanity


## Course Policies

### Late Policy
Because we start homework assignments in class, and material is cumulative, it's very important that readings and assignments are completed by the deadlines they are designed for. At the same time, I understand that life happens! To ensure students have a bit of added flexibility, each student has *3 24-hour late passes*[^2]: 

- Each late pass may be applied to delay one assignment deadline by 24 hours within the semester.
- Any number of available passes may be applied to any assignment deadline. No work is accepted past the end of the final exam period, regardless of available late passes.
- Late passes are not transferable, reusable, or divisible.
- After your late pass budget is exhausted, each additional 24-hour delay in assignment submission is assessed a late penalty that subtracts 10% of the maximum assignment grade from your awarded grade on that assignment.
- To use a late day, you must fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLSfKVleGGJp2-vqECMAscBBZumU5MSD5K88tbeHAx-YXg6l44w/viewform?usp=header) before the assignment deadline.

Importantly, because I designed the group project to be cumulative, and because a primary tenet of group collaboration is being accountable to one another, **late work will not be accepted for the final group project, or any of its checkpoints**. 

If you anticipate an assignment will be late due to an emergency, please email me at least 24 hours before the due date to discuss a path forward. In collaboration with your [class dean](https://www.wellesley.edu/about-us/offices-departments/class-deans#team) and/or [health services](https://www.wellesley.edu/healthservice), we will figure out the best path forward, together.

If you know you will need to miss class due to illness or family emergency, please let me know so we can make a plan for how to proceed.

### Use of Generative AI
In addition to the overwhelming energy and water use that data centers use to answer your queries (a distributional burden that communities like my hometown are now bearing [^3]), generative AI poses significant threats to the learning outcomes of this class. I designed this course to 1) strengthen students' abilities to comprehend and apply justice-based theories, and 2) learn the foundations of data visualization in R. Therefore, I ask that you **do not** use it for the following: 

- Summarizing or annoting readings
- Generating code of any kind 
- Answering any questions on assignments

If you feel that generative AI can be used to improve your knowledge on a topic, or for brainstorming ideas without sacrificing your ability to think critically, *please come speak with me about it, before you employ it in your workflow*. I'm still learning the pros and cons of Generative AI in higher education, and I always welcome the discussion. 

### Course Components

- **Attendance and Participation (10%)**: This primarily includes coming to class prepared (i.e., completed any preparatory readings/assignments before our scheduled course meeting), engaging with peers on course content (i.e., asking questions, sharing thoughts and ideas, participating in group activities).

- **Positionality Statement (5%)**: The first assignment for the course will be a brief statement that explains your positionality and how it might influence your engagement with the course and its materials.

- **Weekly Assignments (60%)**: Each week provides an opportunity to discuss and explore different forms of environmental justice through a community case study. 
    - *Tuesdays* will focus on small and large-group discussions on key theoretical concepts related to that week’s community case study. Please come prepared to discuss the readings.
    - *Fridays* will mainly focus on an in-class data visualization exercise (each worth 10%) related to the weekly case study. Please read the assigned case study and review the exercise before class. Be prepared to work in rotating pairs on the assignment, then submit it individually by the following Thursday at 11:59 PM. 

- **Community Case Study Final Project (25%)**: End of semester group project on a community case study of your choice. Note that final project score is cumulative, including a project plan (10%), data manipulation checkpoint (5%), and final submission (10%). Please see the [Final Project Description](final_project/-desc.qmd) for more information.


### Assessment
My approach to assessment is centered on 1) gauging students' learning as it corresponds to the course learning goals, and 2) providing feedback that facilitates growth. [Wellesley's grading policy](https://www.wellesley.edu/about-us/offices-departments/registrar/grading-policy) aligns with these goals, and uses a relatively qualitative approach: 

   - *Grade A* is given to students who meet with conspicuous excellence every demand that can fairly be made by the course. 
   -  *Grade B* is given to those students who add to the minimum of satisfactory attainment excellence in not all, but some of the following: organization, accuracy, originality, understanding, insight. 
   - *Grade C* is given to those students who have attained a satisfactory familiarity with the content of a course and who have demonstrated ability to use this knowledge in a satisfactory manner.

For individual work (weekly assignments and participation), I will provide written feedback on each learning outcome, along with a score of 1 to 5. For example, feedback on one community case study might look like this: 

| Learning Outcome | Score |
|----------|----------|
| Understand basic tidy data structure  | 4  |
| Transform and tidy data for necessary questions  | 4  |
| Explore and summarize patterns  | 3  |
| Connect it to theoretical understandings of procedural justice  | 5  |


For team work (final group project), I will provide a rubric and grade the product on a percentage scale. 

### Course Readings
There are no textbooks for this course. All course readings will be made available on the website. Please see the [schedule](schedule.qmd) for each week's corresponding material. 

### Living Syllabus
Since this course is in its early development, I reserve the right to make minor adjustments, such as changes to assigned readings (well in advance of class), as needed or based on student feedback to improve the course. 

### Communication
Class emails will be sent out via Brightspace. Please do feel free to [email me](mailto:mc152@wellesley.edu) with questions or concerns regarding the course, and I will do my best to respond within 48 hours (excluding weekends). 

### Accessibility and Disability
Every student has the right to full access in this course. If you find any material difficulty to access due to course format, technology, or any other reason, please don't hesitate to let me know so that we can identify appropriate accommodations.  

Additionally, the Wellesley [Office of Accessibility and Disability Resources (ADR)](https://intranet.wellesley.edu/administrative/accessibility-and-disability-resources) ensures that students receive reasonable and appropriate accommodations including but not limited to: testing accommodations, classroom accommodations, notetaking services, on-campus transportation, communication resources, and assistive technology. In the case that you require accommodations, please be in touch with ADR to request or update an accommodation letter. 

### Religious Observance 
Students observing a religious holiday that conflicts with a scheduled course event are encouraged to speak with me in advance to identify alternative arrangements. Students are also welcome to read more about the College's [Policy on National Holidays and Religious Days of Observance](https://www.wellesley.edu/about-us/policies-procedures/days-of-observance), or submit a [Religious Observance Notification Form](https://webapps.wellesley.edu/religious_calendar/calendar.php). 

### Discrimination, Harassment, and Sexual Misconduct
Wellesley College considers diversity essential to educational excellence, and we are committed to being a community in which each member thrives. The College does not allow discrimination or harassment based on race, color, sex, gender identity or expression, sexual orientation, ethnic or national origin or ancestry, physical or mental disability, pregnancy or any other protected status under applicable local, state or federal law. 

If you or someone you know has experienced discrimination or harassment, support is available to you:

**Confidential Reporting:** Students can report their experiences to Health Services (781-283-2810); Stone Center Counseling Service (781-283-2839); or Religious and Spiritual Life (781-283-2685). *These offices are not required to report allegations of sexual misconduct to the College*.

**Non-Confidential Reporting:** You can let your instructor know. *As faculty, we are obligated to report allegations of sex-based discrimination to the Non-discrimination/Title IX Office*. You can report directly to the Non-discrimination/Title IX Office (781-283-2451) to receive support, and to learn more about your options for a response by the College or about reporting to a different institution. You can report to the Wellesley College Police Department (Emergency: 781-283-5555, Non-emergency: 781-283-2121) if you believe a crime has been committed, or if there is an immediate safety risk.

### Feedback
I sincerely care about your experience in this course, and am always interested to hear your feedback. There are several ways to share your ideas and suggestions: 

- Come talk to me! I know that students are likely to have different learning styles, which means I won't be offended if you share ideas on how to improve things. 
- You can always provide feedback anonymously via this [form](https://docs.google.com/forms/d/e/1FAIpQLSfnbphRazZ99wNWsAbozjeAMZtFMo5qbPRy2QagE74xZUB2Mw/viewform?usp=sharing&ouid=102576151535349337042)
- I'll also collect anonymous feedback about the course at the mid-semester point.

## Important Dates
-   **Jan 20**: First Day of Classes
-   **Feb 16**: No Class, Presidents' Day
-   **Feb 17**: Substitute Day [Monday Classes]
-   **Mar 16-22**: Spring Break
-   **Apr 8:** No Class, Dr. Caballero at a Workshop
-   **Apr 20**: No Class, Patriots' Day
-   **Apr 30**: Substitute Day [Monday Classes]; Last Day of Classes
-   **May 01- 04**: Reading Period
-   **May 05- 08**: Final Exams

## Acknowledgments
This course was created using [templates](https://github.com/rstudio-conf-2022/teach-ds-course-website) created by Maria Tackett & Mine Cetinkaya-Rundel. I'm also very grateful for tips and resources from [Dr. Yaniv Yacoby](https://yanivyacoby.github.io/), [Accessible Syllabus](https://accessiblesyllabus.com/), and faculty feedback from the [Wellesley Environmental Studies Department](https://www.wellesley.edu/academics/department/environmental-studies).

[^1]: brown, adrienne maree. (2024). Loving Corrections. AK Press.

[^2]: Thanks to the Wellesley CS department for their late policy guidelines!

[^3]: Ramadan, L., & Brownstone, S. (2024, July 28). Washington Is Giving Tax Breaks to Data Centers That Threaten the State’s Green Energy Push. ProPublica. https://www.propublica.org/article/data-centers-clean-energy-washington-state
