---
title: "Week 13"
subtitle: "Cosmopolitan Justice in Framingham, MA"
description: "Nov 25 - Nov 28"
author: ""
date: ""
listing:
  - id: slides
    contents:
      - ../slides/week-13/*.qmd
    type: table
    fields: [title, date]
    date-format: "ddd, MMM DD"
    field-display-names:
      title: "Topic"
      date: "Date"
    sort: [filename]
    sort-ui: false
    filter-ui: false
tbl-colwidths: [10,50,40]
---

::: {.callout-important}
Note that our Tuesday class is **hybrid**. To join virtually, please use this [link](https://wellesley.zoom.us/j/94099147794?jst=2). There is no class on Friday, November 28, 2025 due to Thanksgiving Break. 
:::

# Guest Lecturer
Angie Alberto Escobar is Director of Gas to Geo Transition at [HEET](https://www.heet.org/who-we-are), leading efforts to shift from gas to networked geothermal systems with equity at the core. She supports municipalities in assessing geothermal potential, coordinates technical partners, and co-develops engagement strategies that prioritize community leadership and long-term resilience.

# Lectures

::: {#slides}
:::



# Readings
|                                                                                                           |
|-----------------------------------------------------------------------------------------------------------|
|**Tuesday:** Partin et al., (2025). [Chapter one: Introduction and Chapter 4: Equity and Environmental Justice Perspectives on TENs in Thermal Energy Networks in the United States: Emerging Opportunities, Challenges, and Needs](https://drive.google.com/drive/folders/1nuz7C8x2eFGsa3_uq-820xnXIUlQDLHV). Transformative Strategies Consulting. |
|**Tuesday:** PBS News Hour (2025): [Unlikely Alliance Builds Cleaner Geothermal Energy Network](https://www.pbs.org/video/unlikely-alliance-builds-cleaner-geothermal-energy-network-1760136360/). |