---
title: "Week 05"
subtitle: "Restorative (in)Justice in Edgecombe County, NC"
description: "Feb 17 - Feb 19"
author: ""
date: ""
listing:
  - id: slides
    contents:
      - ../slides/week-05/*.qmd
    type: table
    fields: [title, date]
    date-format: "ddd, MMM DD"
    field-display-names:
      title: "Topic"
      date: "Date"
    sort: [filename]
    sort-ui: false
    filter-ui: false
  - id: assignments
    contents:
      - ../hw/w5-*.qmd
    type: table
    fields: [categories, title, date]
    date-format: "ddd, MMM DD"
    field-display-names:
      categories: "Assignment"
      title: "Title"
      date: "Due"
    sort: [date]
    sort-ui: false
    filter-ui: false
tbl-colwidths: [10,50,40]
---

::: {.callout-important}
Note that there is no class on Monday, February 16, 2026. The following day (Tuesday, February 17) will be on Monday schedule.
:::

# Lectures

::: {#slides}
:::

# Assignments

::: {#assignments}
:::

# Readings
| | |
|---------|-------------------------------------------------------------------------|    
|**Monday** |Ibrahim, A. A. (2023). [Empowering Those in Harm’s Way: A Restorative Justice Approach](https://drive.google.com/file/d/1Bv0Y5D2vnxD8RV4g6TVOWXwgZ5776j3M/view?usp=drive_link). In The Power of Energy Justice & the Social Contract (pp. 243-249). Cham: Springer Nature Switzerland.                        |
|**Monday** |Harrison, C. (2016). [Race, space, and electric power: Jim Crow and the 1934 North Carolina rural electrification survey](https://drive.google.com/file/d/1dp6uZGXynx23Kmse9aEtzkIzWFtJxJSh/view?usp=drive_link). Annals of the American Association of Geographers, 106(4), 909-931|
|**Monday** | Listen to [Alvin Morrison's interview](https://dc.lib.unc.edu/cdm/compoundobject/collection/sohp/id/10633/rec/29) from the [Southern Oral History Program](https://dc.lib.unc.edu/cdm/search/collection/sohp/searchterm/D.%20Rural%20Electrification/field/projec/mode/exact/conn/and/order/title) (or read the transcript) on rural electrification in North Carolina.|
|*Optional Thursday*| Wickham, H., Çetinkaya-Rundel, M., & Grolemund, G. (2023). [R for Data Science (2e): Chapters 4 and 5](https://r4ds.hadley.nz/workflow-style.html). Sebastopol: O'Reilly.   |       