---
title: "Week 14"
subtitle: "Restorative Justice in Greater Boston, MA"
description: "Dec 02 - Dec 05"
author: ""
date: ""
listing:
  - id: slides
    contents:
      - ../slides/week-14/*.qmd
    type: table
    fields: [title, date]
    date-format: "ddd, MMM DD"
    field-display-names:
      title: "Topic"
      date: "Date"
    sort: [filename]
    sort-ui: false
    filter-ui: false
tbl-colwidths: [10,50,40]
---
# Guest Lecturer 
Franelis Morillo Suarez ('21) is a Clean Energy & Climate Planner II for the [Metropolitan Area Planning Council](https://www.mapc.org/our-work/expertise/climate/) (MAPC). In her role, she provides technical assistance to communities for their climate mitigation and resilience work in the Greater Boston region, and advocates for centering equity in plans, policies, programs, and community engagement. As an Afro-Latina and a resident of an environmental justice community, she is very passionate about equitably creating more resilient communities while simultaneously mitigating climate change. She is passionate about climate justice and bringing a public health lens into her work, while keeping racial equity at the forefront, especially when it comes to community engagement.

She received a Sustainability Certificate and earned a Bachelor of Arts in Environmental Studies and Italian Studies from Wellesley College. She recently received a Climate Change & Health Certificate from the Yale School of Public Health.

# Lectures

::: {#slides}
:::


# Readings
