---
title: "Week 11"
subtitle: "Procedural Justice in Bar Harbor, ME"
description: "Nov 11 - Nov 14"
author: ""
date: ""
listing:
  - id: slides
    contents:
      - ../slides/week-11/*.qmd
    type: table
    fields: [title, date]
    date-format: "ddd, MMM DD"
    field-display-names:
      title: "Topic"
      date: "Date"
    sort: [filename]
    sort-ui: false
    filter-ui: false
tbl-colwidths: [10,50,40]
---
# Guest Lecturer
[Dr. Jane Disney](https://mdibl.org/faculty/jane-e-disney-ph-d/) is an Associate Professor of Environmental Health at MDI Biological Laboratory in Bar Harbor, ME. Her research involves citizen science to investigate Per- and Polyfluoroalkyl substances (PFAS) contamination in drinking water from private wells in neighborhoods surrounding rural schools in Maine. As the principal investigator of the Community Lab, Dr. Disney has involved 41 teachers from 35 schools and over 5,000 students in Maine and New Hampshire to collect drinking water samples. This work aims to inform public health measures and influence state policies.

# Lectures

::: {#slides}
:::

# Readings
|                                                                                                           |
|-----------------------------------------------------------------------------------------------------------|
|**Tuesday:** Schmitt, K., Minovi, D., Loeb, S., & Ward, M. H. (2024). [A state-by-state comparison of policies that protect private well users](https://drive.google.com/drive/folders/1Bcf-6-YmRordpN3-PL18tvXw9K_lU33N). *Journal of Exposure Science & Environmental Epidemiology*, 34(1), 155-160.|
|**Tuesday:** Taylor, A., Garretson, A., Bieluch, K. H., Buckman, K. L., Lust, H., Bailey, C., ... & Disney, J. E. (2024). [A mixed methods approach to understanding the public health impact of a school-based citizen science program to reduce arsenic in private well water](https://drive.google.com/drive/folders/1Bcf-6-YmRordpN3-PL18tvXw9K_lU33N). *Environmental Health Perspectives*, 132(8), 087006.|
