---
title: "[Theory] Distributional (in)Justice"
subtitle: "📍Houston, TX"
date: "September 09, 2025"
format: 
  revealjs:
    theme:
      - default
    css: custom.scss
    transition: fade
    slide-number: true
    incremental: false 
    chalkboard: true
    center: true
execute:
  freeze: auto
---

#  Class Overview 
- Centering activity
- What is EJ? 
  - Our definition of EJ 
  - 17 principles of EJ + Tenet-based approach
- Group Discussion
  - Origins of EJ
  - Paired conversations on distributional justice
- Group synthesis
- Intro to community case study (Houston, TX, 1979)

# Centering Activity 
Julia

## What we Read {.smaller}
- Murdock, E. G. (2020). [A history of environmental justice: Foundations, narratives, and perspectives](https://ebookcentral.proquest.com/lib/well/reader.action?docID=6228917&ppg=40&c=RVBVQg). In *Environmental justice* (pp. 6-17). Routledge.
- Kaswan, A. (2020). [Distributive environmental justice](https://ebookcentral.proquest.com/lib/well/reader.action?docID=6228917&ppg=58&c=RVBVQg). In *Environmental justice* (pp. 21-36). Routledge.

# What is EJ? 

## What we know
- <span style="color:red;"> In groups of 4: draft your definition of Environmental Justice, be ready to share! </span>

## Similarities/Differences in definitions?

## Origins of EJ {.smaller}
- Term "environmental justice" was popularized in 1980s
- **1982:** Began as a social movement
  - Communities of color organizing and resisting unfair siting activities (toxic waste, landfills, and oil refineries)
  - Protests in Warren County, NC are especially salient to EJ movement
- **1987:** United Church of Christ (UCC) Commission for Racial Justice published report on Black and Latine exposure to toxic sites. 
- **1991:** UCC hosted the First National People of Color Environmental Leadership Summit, where the 17 Principles of Environmental Justice were created

## 17 Principles of EJ + Tenet-Based Approach
- 17 Principles are still highly regarded
-  A lot of academic conversations around what EJ means to whom, and how to classify it.
  - lmk if you want more readings suggestions on this
- I chose a five tenet approach (currently used a lot in Energy Justice scholarship), because I think it provides a nice framework for theorizing different aspects of justice.

## Principles + Tenet Sorting
- <span style="color:red;"> In groups of 4: Sort the 17 Principles of EJ into the five tenets, be ready to discuss! </span> 

## Sorting Results
- Defining Environmental Justice is tricky, and many definitions/approaches will overlap. 
  - This can be both a strength and a challenge. 
  - (If I could make this course 34 weeks long, I would!)
 


# Positionality statement debrief

# Paired conversations on Distributional Justice

- 

# Group Synthesis

# Intro to Community Case Study

## Overview

## Theoretical Applications 

## Why I chose this case study

## Assessment Approach

## Outcomes of this case study

# Logistics
For Friday: 

- Read community case study in schedule
- Review in-class activity
- Make sure posit login is working!
