---
title: "Dr. Caballero's Positionality Statement"
date: "September 08, 2025"
categories: "Homework"
---

My name is Mariah Caballero. I am the proud daughter of two elementary educators: a Mexican American father and a white mother. My mixed heritage, cultures, and family often mean that I exist liminally in both. At times, I see my heritage and cultures at odds in my community and family. I grew up as a third-generation member in rural eastern Washington. My community is predominantly Latine and depends on industrial agriculture to support its economy, an unequal relationship that began far before my grandparents immigrated to the States. I am the first in my family to receive my PhD, and I am beginning my career as an assistant professor of environmental studies at Wellesley College.  

My upbringing was centered on education. From an early age, my parents taught me that in addition to upward mobility, education can be liberatory and can serve your community. In my research and teaching, I strive to embody the latter. I’ve also witnessed the role that *intersecting systems of oppression* play within my own family. For example, white supremacy unequally benefits some of my family members (myself included), while harming others. At the same time, I recognize that I am the product of two people who continue to choose dignity, belonging, and love for one another over divisiveness. Given my lived experiences, I strive to create a learning environment committed to individual and community growth, so that we all might be better suited to challenge regressive policies and identity-based beliefs that separate us. 

