---
title: "HW 02: Solid Waste Sites Case Study"
date: "February 11, 2026"
categories: "Homework"
---


## Overview 
This case study focuses on recreating Dr. Robert Bullard's foundational study, "Solid Waste Sites and the Black Houston Community" in R, and connecting it back to foundational theoretical aspects of distributional justice. 

## Learning Outcomes
- Demonstrate basic uses of R, namely formatting a .qmd assignment
- Recreate tables 1-3 in Bullard's Study 
- Visualize Distributional Justice
- Connect it to theoretical understandings of distributional justice


## Instructions
Download the project file [here](https://drive.google.com/drive/folders/12UpHYNcs2aEt4zmJxByd8ft2K932CS5r?usp=sharing) to your computer and complete the assignment in Rstudio.

Render your .qmd file as a pdf and submit it to Brightspace. Please ensure to limit unnecessary warnings and messages that clutter the file by adjusting options in the code chunk. 

## Grading

Case studies are each 10% of your grade.

## Submission
Please submit this assignment to Brightspace by **Wednesday, February 11, 2026 at 11:59 PM**.