---
title: "HW 05: Coastal Livelihoods Case Study"
date: "October 09, 2025"
categories: "Homework"
---

## Overview 
This case study focuses on publicly-available data from federal organizations such as the Federal Emergency Management Agency (FEMA), the Department of Transportation (DOT), the Centers for Disease Control (CDC), and the National Oceanic and Atmospheric Administration (NOAA) to understand the distributional and recognitional challenges facing Isle de Jean Charles.

## Learning Outcomes
- Transform and summarize data for plotting
- Learn how layers in ggplot2 work together to create a plot
- Summarize patterns from open-source data
- Connect findings to theoretical understandings of recognition justice

## Instructions
1. Navigate to [Posit Cloud](https://posit.cloud/spaces/686564/content/all?sort=name_asc) and select the HW 05 assignment. 
2. Follow along in class, and complete the assignment (if needed) outside of class.
3. Render the quarto document as a pdf.

## Grading

Case studies are each 10% of your grade.


## Submission
Submit the pdf to Brightspace [here](https://brightspace.wellesley.edu/d2l/lms/dropbox/user/folders_list.d2l?ou=7420&isprv=0).