---
title: "HW 06: COP Delegate Case Study"
date: "October 16, 2025"
categories: "Homework"
---

## Overview 
This case study uses delegate data from over 30 years of international climate change conferences published open source in a [Nature Scientific Dataset](https://www.nature.com/articles/s41597-024-03978-7), and connecting it back to foundational theoretical aspects of cosmopolitan justice.

## Learning Outcomes
- Apply thematic components to ggplot figures 
- Conduct Exploratory Data Analysis (EDA)
- Understand data visualization options for different data relationships
- Connect findings to theoretical understandings of cosmopolitan justice

## Instructions
1. Navigate to Posit Cloud and select the HW 06 assignment. 
2. Follow along in class, and complete the assignment (if needed) outside of class.
3. Render the quarto document as a pdf.

## Grading

Case studies are each 10% of your grade.


## Submission
Submit the pdf to Brightspace [here](https://brightspace.wellesley.edu/d2l/lms/dropbox/user/folders_list.d2l?ou=7420&isprv=0).

