---
title: "HW 07: Solar Energy Case Study"
date: "March 25, 2026"
categories: "Homework"
---
## Overview 
This case study uses data on solar development  data from the National Renewable Energy Lab's [Screening Tool for Equitable Adoption and Deployment of Solar](https://data.nrel.gov/submissions/238) and energy burden data from the Department of Energy's [Low-Income Energy Affordability Data Tool](https://www.energy.gov/scep/slsc/lead-tool), and connecting it back to the five tenets of EJ. 

## Learning Outcomes
- Read spatial data and transform its projection 
- Create a Chloropleth Map
- Creating a Bivariate Map
- Connect findings to theoretical understandings of the five tenets of Environmental Justice

## Instructions
Download the project file [here]() to your computer and complete the assignment in Rstudio.

Render your .qmd file as a pdf and submit it to Brightspace. Please ensure to limit unnecessary warnings and messages that clutter the file by adjusting options in the code chunk. 

## Grading

Case studies are each 10% of your grade.

## Submission
Please submit this assignment to Brightspace by **March 25, 2026 at 11:59 PM**.

