---
title: "Final Project Description"
date: "December 09, 2025"
categories: "Final Project"
---
## Overview
The final group project is intended to assess your theoretical and methodological skills in environmental justice. Teams are tasked with creating a multimedia narrative of one environmental justice theme (food, energy, water, waste, or climate) based on a community case study of their choice. Final project reports should include both a visual and narrative component: 

- **Visual Component:** Use data to demonstrate environmental injustice occurring in a community of your choice using *at least three data visualizations*
- **Narrative Component:** Provide background information on the community of interest, apply *two or more theoretical tenets of justice* to describe an unjust process, and propose a more equitable intervention using a basic logic model (1500 words) 

## Team Selection
Teams will be based on a combination of 1) anonymous student preferences for teammates (complementary disciplinary strengths and experiences, and coordinating schedules) and 2) my discretion. Teams will comprise 2-3 people. 

Although working in groups can be challenging, it is also a critical component of interdisciplinary research-- we cannot know everything, and often, it makes far more sense to lean on others' expertise. Moreover, team-based work is a **critical component** of organizing for Environmental Justice. To help support team-based work, I will provide time throughout the course to work on final projects and groups will receive feedback from peers. 

## EJ Data Sources
Please see [Data Sources](data_sources.qmd) for a list of potential data sources related to food, energy, water, waste, and climate. 

## Timeline
The final group project is cumulative, because I'm interested in students learning the *process* of interdisciplinary, collaborative research. Several components are due throughout the semester to help complete it. Deadlines include: 

- [**Project Proposal:**](w8-project_proposal.qmd) Thursday, October 30, 2025 at 11:59 PM
- [**Project Plan:**](w10-project_plan.qmd) Friday, November 07, 2025 at 11:59 PM
- [**Final Project:**](w15-final_project.qmd) Friday, December 09, 2025 before class

### Acknowledgements
Thanks to Dr. Matthew Brett's [Data Science for Everyone course](https://matthew-brett.github.io/dsfe/projects/data), and [UC Berkeley's Data and Justice course](https://docs.google.com/document/d/e/2PACX-1vStSkib8yxUyashb3KGHcWr1bdTY5dlncSqlInNX67baLc1zAxWm6S2MrpxwfqMAYXjNzuTACtGc3Kc/pub?urp=gmail_link&gxids=7628), whose open-source syllabi served as inspiration for this assignment. 