---
title: "Final Project"
date: "December 09, 2025"
categories: "Final Project"
---

## Overview


## Team Selection

## FEWs Data Sources

## Timeline
### Project Proposal (by email-- due Friday October 17)

### Project Plan (Friday October 31)


## Rubric

Rubric from [data Science for Everyone](https://matthew-brett.github.io/dsfe/projects/rubric)
From [Data 4AC course](https://docs.google.com/document/d/e/2PACX-1vStSkib8yxUyashb3KGHcWr1bdTY5dlncSqlInNX67baLc1zAxWm6S2MrpxwfqMAYXjNzuTACtGc3Kc/pub?urp=gmail_link&gxids=7628): 
Students will work in teams of 3-4 to create a multimedia narrative of justice about a case study of their own choosing. The project should not only make an argument, but also tell a story using data to describe a problem of justice in the datafied world.

We understand that it can be challenging to work as a group, especially when we cannot meet in-person, but team-work is also a skill that is central to working in the real-world and we believe that the relationships you form in class are an essential part of learning and can provide lasting satisfaction and meaning. We will support you through the team-making process by facilitating group work throughout the semester where you can learn about and from each other and by providing class time to work on your projects.


Each Narrative must include the following components:

- One textual component of at least 1,000 words (narrative or expository)
- At least three data visualizations of at least two different types
- One additional kind of storytelling media
 - Podcast
 - Video
 - Quarto Document
 - Map or diagram

We will work up to the final project, including: 
- Project proposal (group): A short (approx. 500 word) description of the project you and your group are planning to undertake.
- Project plan (group): A plan detailing the issues, deliverable, concept, data resources, any community partners, and team member responsibilities for your course project. Each team will present their plan to peers during section discussion and receive feedback from peers and instructors.
- Completed course project and presentation (group): Submit your course project and deliver a 10-minute presentation in the last week of class during one of the lecture times to classmates, community members, Berkeley faculty and invited guests to celebrate your project.

Completed course projects are due on the day of your presentation, either 2pm PST T 4/27 or Th 4/29.